import os, json

with open("index.html") as fd:
    template = fd.read()

path = os.path.abspath(__file__)
path = os.path.dirname(path)
files = os.listdir(path)

jsCode = ""
cssCode = ""
for filename in files:
    with open(filename) as fd:
        content = fd.read()

    if filename.endswith(".js"):
        jsCode += content + "\n"
    if filename.endswith(".css"):
        cssCode += content + "\n"

template = template.replace("%js%", jsCode)    
template = template.replace("%css%", cssCode)

with open("bundle.html", "w") as fd:
    fd.write(template)

with open("bundle.hpp", "w") as fd:
    fd.write("#pragma once\n\n//autogenerated by generate-bundle.py\nconst char webpageData[] = ")
    json.dump(template, fd)
    fd.write(";\n//end")
