import os, re, gzip

with open("index.html") as fd:
    template = fd.read()

path = os.path.abspath(__file__)
path = os.path.dirname(path)
files = os.listdir(path)

jsCode = ""
cssCode = ""
for filename in files:
    with open(filename) as fd:
        content = fd.read()

    if filename.endswith(".js"):
        jsCode += content + "\n"
    if filename.endswith(".css"):
        cssCode += content + "\n"

template = template.replace("%js%", jsCode)    
template = template.replace("%css%", cssCode)

#template = re.sub("\\s+", " ", template)
compressed = gzip.compress(template.encode("utf8"))

with open("bundle.html", "w") as fd:
    fd.write(template)

with open("bundle.hpp", "w") as fd:
    fd.write("#pragma once\n#include <stdint.h>\n\n//autogenerated by generate-bundle.py\n")
    fd.write("//{} bytes of gzipped html (uncompressed: {} bytes)\n".format(len(compressed), len(template)))
    fd.write("const uint8_t webpageData[] PROGMEM = {\n")
    for i, val in enumerate(compressed):
        fd.write("{0:#04x}, ".format(val))
        if i % 16 == 15:
            fd.write("\n")
    fd.write("\n};\n//end")
